// Auto-generated by scripts/deploy-demo.js
window.MUZZLE_CONFIG = {
  "realMuzzleToken": "0xef3dAa5fDa8Ad7aabFF4658f1F78061fd626B8f0",
  "realChainId": 1,
  "realChainName": "Ethereum Mainnet",
  "tokenSymbol": "MUZZ",
  "tokenDecimals": 18,
  "flatPriceMuzzle": "800000",
  "flatPriceUsd": "2.00",
  "refPriceUsdPerMuzzle": "0.0000025",
  "burnAddress": "0x000000000000000000000000000000000000dEaD",
  "burnBps": 10000,
  "walletConnectProjectId": "",
  "demo": {
    "chainId": 31337,
    "chainName": "Hardhat Local",
    "rpcUrl": "http://127.0.0.1:8545",
    "muzzleToken": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "muzzleName": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "minter": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0"
  },
  "sepolia": {
    "chainId": 11155111,
    "chainName": "Sepolia",
    "rpcUrl": "https://ethereum-sepolia-rpc.publicnode.com",
    "explorer": "https://sepolia.etherscan.io",
    "muzzleToken": "",
    "muzzleName": "",
    "minter": "",
    "isMockToken": true
  },
  "mainnet": {
    "muzzleName": "",
    "minter": ""
  },
  "deployedAt": "2026-09-13T18:16:45.451Z"
};
